Issue 1 create an entry
louis-zhangxa/code-journal pull request #5
Opened 2022-11-01 17:38 UTC by louis-zhangxa

https://user-images.githubusercontent.com/114542582/199300515-b9623d1e-f670-4b5c-aa3c-08a28011f11c.mov

https://user-images.githubusercontent.com/114542582/199300638-758c73c5-392f-4652-9399-3cb1897e2600.mov

2022-11-01 17:52 UTC, louis-zhangxa commented
![Screen Shot 2022-11-01 at 10 52 36 AM](https://user-images.githubusercontent.com/114542582/199303494-e5d13117-5a6d-4eab-a14f-abf92aad1450.png)

2022-11-01 17:55 UTC, louis-zhangxa commented
![Screen Shot 2022-11-01 at 10 55 13 AM](https://user-images.githubusercontent.com/114542582/199304028-182ee17e-21d0-4c1e-afcc-9849310bd923.png)

2022-11-01 18:36 UTC, codingcodymiller requested changes

2022-11-01 18:36 UTC, codingcodymiller commented on css/styles.css
> +  }
What are you using this for? Why not just use the `row` class?

2022-11-01 18:36 UTC, codingcodymiller commented on css/styles.css
> +  }
why are you setting `width` directly? you should be using `column-` classes to regulate element's size, and using the `container` class to restrict the size of the page as a whole

2022-11-01 18:36 UTC, codingcodymiller commented on index.html
> +      <h3>Code Journel</h3>
You misspelled "journal". Also, you should have elements with the `container`, `row`, and `column` classes in here.

2022-11-01 18:36 UTC, codingcodymiller commented on index.html
> +    </div>
Where are your layout classes? I gave you a bunch of them in `layout.css`

2022-11-01 18:36 UTC, codingcodymiller commented on index.html
> +    </div>
this layout needs to be done using proper layout classes.

2022-11-01 18:36 UTC, codingcodymiller commented on js/main.js
> +});
You shouldn't do this on each `input` event, you should just collect these values when the `submit` event occurs in the `submit` event handler.

2022-11-01 18:36 UTC, codingcodymiller commented on js/main.js
> +  data.entries.push(userNote);
You should be adding to the beginning, not the end.

2022-11-01 18:36 UTC, codingcodymiller commented on js/main.js
> +  data.nextEntryId++;
You did not add an id to the `userNote` entry object.

2022-11-01 18:36 UTC, codingcodymiller commented on js/main.js
> +$submit.addEventListener('click', submitNote);
This should be a `submit` event listener on the `form` element, not a `click` event listener on the submit button. Please review `javascript-forms` for a refresher on how to handle this correctly.

2022-11-01 18:36 UTC, codingcodymiller commented on js/main.js
> +}
This should be in `data.js`, in the same file as the variable it is preserving.

2022-11-01 18:36 UTC, codingcodymiller commented on js/main.js
> +function string(event) {
`string` is a **_terrible_** function name. how about `storeDataInLocalStorage`?

2022-11-02 00:04 UTC, codingcodymiller requested changes

2022-11-02 00:04 UTC, codingcodymiller commented on js/data.js
> +$submit.addEventListener('submit', storeDataInLocalStorage);
This should be a `beforeunload` event listener, not a `submit` event listener on the `form`. LocalStorage is for saving data for future sessions, which means it only makes sense to update its value right before this session ends. It does not need to be updated every time the form is submitted

2022-11-02 02:42 UTC, codingcodymiller approved these changes

2022-11-02 07:55 UTC, merged